
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eli
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eli
  template:
    metadata:
      name: eli
      labels:
        app: eli
    spec:
      containers: 
      - name: eli-pod
        image: elilaiono/cit270
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run", "start"]
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret-elijah
              key: REDIS_PASS
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret.eli
---
apiVersion: v1
kind: Service
metadata:
  name: eli-loadbalencer
spec:
  selector:
    app: eli
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
      